/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Builder b = new BuilderCasa();
        b.setDoors(3);
        b.setWalls(4);
        b.setWindows(3);
        b.setHasGarage(true);

        System.out.println(b.build());
    }
}
