/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.time.LocalDate;

public class App {


    public static void main(String[] args) {
        CalendarLibrary calendarLibrary = new CalendarLibrary(
            LocalDate.of(2025, 1, 1),
             LocalDate.of(2025, 12, 31)
             );
        CalendarAdapter calendarAdapter = new CalendarAdapter(calendarLibrary);
        calendarAdapter.add("Event 1", LocalDate.of(2025, 1, 1));
        calendarAdapter.add("Event 2", LocalDate.of(2025, 1, 2));
        calendarAdapter.getAll();
    }
}
