/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;


public class App {

    public static void main(String[] args) {
        Car c1 = new Car();
        c1.setColor("red");
        c1.setModel("208");

        Car c2 = (Car) c1.clone();

        System.out.println(c1);
        System.out.println(c2);


    }
}
